### ISSUE TITLE
Terraform config - data.aws_caller_identity.current.account_id not enclosed properly

### ISSUE THREAD

**Issue by rjlupinek** [GSA/grace-inventory#20]
**File:** main.tf
**Line:** 6

The reference for id from the data source aws_caller_identity is not properly enclosed in `"${}"`.
Is currently:
`account_id     = data.aws_caller_identity.current.account_id`
Should be:
`account_id     = "${data.aws_caller_identity.current.account_id}"`

Error thrown:

```
Error: MalformedPolicyDocumentException: Policy contains a statement with one or more invalid principals.
	status code: 400, request id: 2425f0db-3033-448c-8e20-347eec8cac03

  on .terraform/modules/example_self/kms.tf line 1, in resource "aws_kms_key" "kms_key":
   1: resource "aws_kms_key" "kms_key" {
```

**Comment by briankfitzwater** [comment]
@rjlupinek What version of Terraform are you using?  The module requires >=v0.12.  The syntax is valid in v0.12+.  We sometimes see this error when there is a race condition where a required principle, possibly an IAM role, hasn't been completed before a policy is being implemented. We try to prevent with the "depends on" attribute in the kms key resource.  However, sometimes we get the error anyway but re-applying the terraform usually resolves it.

**Comment by briankfitzwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [grace-inventory: Terraform config - data.aws_caller_identity.current.account_id not enclosed properly (Issue #20)](https://trello.com/c/HcJbzmnT/1478-grace-inventory-terraform-config-dataawscalleridentitycurrentaccountid-not-enclosed-properly-issue-20)

**Comment by rjlupinek** [comment]
Interesting.  I changed my repo I am pulling the module from back to this one, and it worked today.
I have been using this container:  `hashicorp/terraform:latest`

It is reporting as running the following version of terraform:

`Terraform v0.12.16`

I am not getting the error from yesterday.   I am going to try running destroy and the apply again from the start.  I will report back soon.

**Comment by rjlupinek** [comment]
I ran a destroy and apply in my pipeline and everything came back green.  
I am at a loss as to what may have changed.  Perhaps an issue of what is cached for terraform:latest in Circle's environment?  Either way, it is running without errors or deprecation warnings.
