### ISSUE TITLE
Bucket region issue when Lambda triggers

### ISSUE THREAD

**Issue by rjlupinek** [GSA/grace-inventory#22]
When the Lambda triggers it looks like I am getting an error due to the region I deployed my infrastructure.

`  failed to upload report to bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2' status code: 400, request id: BC04B1B8AED32969, host id: Cx3IjHtCIrQnS0wX`

I set everything to build in `us-east-2`.  I am going to see if I cannot correct this by moving my S3 bucket for inventory to `us-east-1` as I suspect that is the issue.

**Comment by rjlupinek** [comment]
I comfirmed changing region to us-east-1 from us-east-2 for all resources corrected the issue.  I now have an inventory file.

**Comment by briankfitzwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [grace-inventory: Bucket region issue when Lambda triggers (Issue #22)](https://trello.com/c/zbpW94mK/1486-grace-inventory-bucket-region-issue-when-lambda-triggers-issue-22)

**Comment by rjlupinek** [comment]
Hey team.  It looks like you gentlemen were correct on our last call.  When switching the order of regions the first region is assigned the default.  We swapped it and go this error:


```
21:19:39
failed to upload report to bucket: BucketRegionError: incorrect region, the bucket is not in 'us-east-2' region at endpoint '' status code: 301, request id: , host id: : errorString null
failed to upload report to bucket: BucketRegionError: incorrect region, the bucket is not in 'us-east-2' region at endpoint ''
	status code: 301, request id: , host id: : errorString
null
```

Let me know if you want to setup a test session.
