### ISSUE TITLE
typeToSheet should contain all supported types

### ISSUE THREAD

**Issue by bryanlalexander** [GSA/grace-inventory#39]
As noted in Issue #38 a bug was identified where `*elbv2.LoadBalancer` did not exist in the [typeToSheet](https://github.com/GSA/grace-inventory/blob/master/handler/inv/inv.go#L305) method causing report generation failure.

All known and supported types should be present in `typeToSheet`, I have compiled a quick list of items not covered by the `typeToSheet` method. As the method is being resolved, each type should likely have a test for `typeToSheet` that verifies at minimum there is no error.

| Sheet | Type | Missing |
| ----- | ---- | ------- |
| SheetRoles | *iam.Role | False |
| SheetGroups | *iam.Group | False |
| SheetPolicies | *iam.Policy | False |
| SheetUsers | *iam.User | False |
| SheetBuckets | *s3.Bucket | False |
| SheetInstances | *ec2.Instance | False |
| SheetImages | *ec2.Image | False |
| SheetVolumes | *ec2.Volume | False |
| SheetSnapshots | *ec2.Snapshot | False |
| SheetVpcs | *ec2.Vpc | False |
| SheetSubnets | *ec2.Subnet | False |
| SheetSecurityGroups | *ec2.SecurityGroup | False |
| SheetAddresses | *ec2.Address | **True** |
| SheetKeyPairs | *ec2.KeyPairInfo | **True** |
| SheetStacks | *cloudformation.Stack | **True** |
| SheetAlarms | *cloudwatch.MetricAlarm | **True** |
| SheetConfigRules | *configservice.ConfigRule | False |
| SheetLoadBalancers | *elbv2.LoadBalancer | **True** |
| SheetVaults | *glacier.DescribeVaultOutput | False |
| SheetKeys | *helpers.KmsKey | False |
| SheetDBInstances | *rds.DBInstance | False |
| SheetDBSnapshots | *rds.DBSnapshot | False |
| SheetSecrets | *secretsmanager.SecretListEntry | False |
| SheetSubscriptions | *sns.Subscription | False |
| SheetTopics | *helpers.SnsTopic | False |
| SheetParameters | *ssm.ParameterMetadata | False |

**Comment by briankfitzwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[grace-inventory] typeToSheet should contain all supported types (Issue #39)](https://trello.com/c/dq3QVmNs/1622-grace-inventory-typetosheet-should-contain-all-supported-types-issue-39)
