### ISSUE TITLE
Error setting resource tags

### ISSUE THREAD

**Issue by partha-gsa** [GSA/grace-inventory#44]
Looks like some circular dependency

Error: error updating S3 Bucket (test123-development-inventory) tags: error setting resource tags (test123-development-inventory): NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: 945A07546A79C49D, host id: J5HUtj/dTQ33E3IzpXE5nyuIxkhSi3XKkRB52EQYkIiPV3Yn+axT01TVOi/elJzy9uJPVz5kOz8=

  on .terraform/modules/grace_inventory/s3.tf line 1, in resource "aws_s3_bucket" "bucket":
   1: resource "aws_s3_bucket" "bucket" {

**Comment by briankfitzwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[GSA/grace-inventory] Error setting resource tags (#44)](https://trello.com/c/o2O3ZL3z/1877-gsa-grace-inventory-error-setting-resource-tags-44)

**Comment by briankfitzwater** [comment]
@partha-gsa Did release v0.1.6 fix your issue?

**Comment by briankfitzwater** [comment]
@partha-gsa I scheduled a follow-up meeting to link up and do some troubleshooting today at 1:30PM ET

**Comment by briankfitzwater** [comment]
@partha-gsa Is this working now?

**Comment by briankfitzwater** [comment]
@partha-gsa Is this issue resolved?
